version: '2'
services:
  web:
    build: .
    image: djangobase
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - migration
      - db
  db:
    image: postgres:10.1
    volumes:
      - .:/tmp/data/
  migration:
    image: djangobase
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
